name: Dependency review

on:
  pull_request:
    branches:
      - dev
      - master

permissions:
  contents: read

jobs:
  dependency-review:
    name: Review dependency changes
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Review dependencies
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
